spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ch
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create   # 개발 시에는 create/update, 운영에서는 validate 추천
    show-sql: true
    properties:
      hibernate.format_sql: true

  thymeleaf:
    cache: false
